# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MTKIT' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod 'Masonry', '~> 1.1.0'

  # Pods for MTKIT

  target 'MTKITTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MTKITUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
